bsideproject/startrail-front-end

- src/styles/abstracts/_mixin.scss
- src/styles/pages/_login.scss
- src/styles/style.scss
style.scss 에서 @forward 구문으로 필요한 scss 파일들을 import 하면 됩니다.
> sass 구조 변경

- src/components/main/MainFriendList.tsx
> feat: 메인페이지 관계 레벨 구현

- .env
- src/components/main/MainFilterBtn.tsx
- src/components/main/MainSearch.tsx
- src/pages/main/Main.tsx
- src/store/FriendStore.ts
Reverts bsideproject/startrail-front-end#71
> Revert "env file delete"

- src/components/common/Calendar.tsx
> feat: merge error fixed

- package-lock.json
feat: package-lock.json upload
> feat: package-lock.json upload

- src/pages/mind/Event.tsx
- src/pages/mind/FriendList.tsx
feat: modal backgrount color changed
> feat: modal backgrount color changed

- src/components/common/InputTextBox.tsx
- src/components/common/InputTextBoxWithArrow.tsx
- src/pages/friend/Friend.tsx
- src/pages/main/Main.tsx
- src/store/FriendStore.ts
- src/styles/abstracts/_common.scss
- src/styles/pages/_main.scss
> feat: 관계 등록 페이지 개발 완료

- src/components/main/MainFriendList.tsx
- src/pages/detail/Detail.tsx
- src/store/FriendStore.ts
feat: 관계 상세 페이지 - 친구 상세 정보 api 호출
> feat: 관계 상세 페이지 - 친구 상세 정보 api 호출

- src/pages/detail/Detail.tsx
feat: api 호출 전 데이터 바인딩 되는 오류 해결
> feat: api 호출 전 데이터 바인딩 되는 오류 해결

- src/components/detail/ExchangeWrap.tsx
- src/pages/mind/Mind.tsx
- src/store/FriendStore.ts
- src/store/MindStore.ts
- src/styles/pages/_detail.scss
> feat: 상세페이지 주고 받은 내역 마크업

- src/components/detail/ExchangeWrap.tsx
- src/pages/detail/Detail.tsx
- src/pages/friend/Friend.tsx
- src/pages/main/Main.tsx
- src/store/FriendStore.ts
- src/styles/pages/_detail.scss
- src/utils/DateUtil.ts
> feat: 상세페이지 기능 구현 완료

- src/components/detail/ExchangeWrap.tsx
> feat: 상세페이지 금액 로직 수정

- public/index.html
feat: 모바일 화면 입력창 클릭 시 화면 확대 방지 meta tag add
> feat: 모바일 화면 입력창 클릭 시 화면 확대 방지 meta tag add

- public/index.html
- src/App.tsx
- src/components/main/MainText.tsx
- src/pages/main/Main.tsx
- src/pages/setting/Setting.tsx
- src/pages/setting/SettingNickname.tsx
- src/pages/setting/SettingOptIn.tsx
- src/pages/setting/SettingTerms.tsx
- src/pages/setting/SettingWithdrawal.tsx
- src/store/FriendStore.ts
- src/styles/pages/_setting.scss
- src/styles/style.scss
> feat: markup setting page

- src/App.tsx
- src/pages/setting/SettingNickname.tsx
- src/store/FriendStore.ts
> feat: 코드 정리

- src/pages/setting/SettingTerms.tsx
> feat: text 수정

- src/App.tsx
> feat: 주석 제거

- src/App.tsx
- src/components/detail/ExchangeWrap.tsx
- src/styles/pages/_detail.scss
> feat: 상세페이지 하단 아이콘, css 수정

- src/App.tsx
- src/components/common/DatePickers.tsx
- src/components/main/MainExchangedCount.tsx
- src/pages/friend/Friend.tsx
- src/pages/main/Main.tsx
- src/styles/abstracts/_common.scss
- src/styles/pages/_friend.scss
- src/styles/pages/_main.scss
- src/styles/pages/_mind.scss
> feat: 퍼블리싱 QA 수정사항 진행

- src/pages/friend/Friend.tsx
- src/pages/mind/Mind.tsx
feat: 관계 등록 - 음력 텍스트 추가, 마음 등록 - placeholder 수정
> feat: 관계 등록 - 음력 텍스트 추가, 마음 등록 - placeholder 수정

- src/pages/setting/SettingTerms.tsx
> feat: 이용약관, 개인정보 처리방침 링크 추가

- src/components/common/DatePickers.tsx
- src/components/common/InputTextBox.tsx
- src/components/common/InputTextBoxWithArrow.tsx
- src/components/detail/LevelCard.tsx
- src/pages/detail/Detail.tsx
- src/pages/friend/Friend.tsx
- src/pages/main/Main.tsx
- src/pages/mind/Event.tsx
- src/pages/mind/FriendList.tsx
- src/pages/mind/Mind.tsx
- src/prototypes/common/LevelInformationProto.ts
- src/store/FriendStore.ts
- src/styles/pages/_mind.scss
1. 메인 화면에서 친구 리스트 안 불러와지는 거 수정
2. 데이트피커에서 오늘 날짜로 세팅 되게끔 수정
3. 마음 등록 - 이벤트 등록 시 기타 선택 후 기타 이벤트명 입력하면 '저장' 버튼 활성화되도록 수정
4. 관계 등록에서 여러명 선택시 생일 입력 비활성화되도록 수정
5. 관계 등록에서 입력값 제대로 체크안되는 거 수정
6. 상세 페이지에서 + 버튼 누르면 바로 마음 등록으로 넘어가도록 수정
7. 마음 등록 - 여러명 했을 때 api로 제대로 데이터 넘어가도록 수정
8. 마음 등록 - 친구 검색에서 검색 결과 없으면 검색 결과 없다 고 알려주는 텍스트 추가
> 마음, 관계 등록 및 메인 화면 버그 수정

- src/styles/pages/_detail.scss
> feat: detail page css fixed

- src/pages/main/Main.tsx
feat: ios main page api call error
> feat: ios main page api call error

- src/pages/main/Main.tsx
feat: app loading spinner error fixed
> feat: app loading spinner error fixed

- src/pages/main/Main.tsx
feat: app loading spinner error fixed - 2
> feat: app loading spinner error fixed - 2

- src/pages/main/Main.tsx
- src/styles/abstracts/_common.scss
feat: app loading spinner error fixed - 3
> feat: app loading spinner error fixed - 3

- src/pages/main/Main.tsx
feat: app loading spinner error fixed - 4
> feat: app loading spinner error fixed - 4

- src/pages/main/Main.tsx
- src/store/FriendStore.ts
- src/store/MindStore.ts
feat: app loading spinner error fixed - 5
> feat: app loading spinner error fixed - 5

- src/App.tsx
- src/pages/main/Main.tsx
- src/store/FriendStore.ts
feat: app loading spinner error fixed - 6
> feat: app loading spinner error fixed - 6

- src/App.tsx
- src/pages/main/Main.tsx
- src/store/MindStore.ts
feat: app loading spinner error fixed - 7
> feat: app loading spinner error fixed - 7

- src/pages/main/Main.tsx
- src/pages/setting/Setting.tsx
- src/pages/setting/SettingNickname.tsx
- src/styles/pages/_main.scss
> feat: main page restitution

- src/components/common/TitleWrap.tsx
- src/pages/setting/SettingTermDetail.tsx
- src/pages/setting/SettingTerms.tsx
- src/styles/pages/_detail.scss
- src/styles/pages/_setting.scss
feat: 이용약관 간격, 크기, 뒤로가기 버튼 추가/수정, 상세페이지 bottom sheet 수정
> feat: 이용약관 간격, 크기, 뒤로가기 버튼 추가/수정, 상세페이지 bottom sheet 수정

- src/App.tsx
- src/pages/main/Main.tsx
- src/pages/setting/SettingOptIn.tsx
- src/styles/pages/_setting.scss
feat: 회원 탈퇴 아이콘 수정, 이벤트 동의 체크 여부 수정, 메인 페이지 마운트 수정
> feat: 회원 탈퇴 아이콘 수정, 이벤트 동의 체크 여부 수정, 메인 페이지 마운트 수정

- src/pages/main/Main.tsx
> feat: main page mount fixed

- src/pages/main/Main.tsx
feat: main page mount fixed - 2
> feat: main page mount fixed - 2

- src/pages/main/Main.tsx
feat: main page mount fixed - 3
> feat: main page mount fixed - 3

- src/pages/main/Main.tsx
feat: main page mount fixed - 4
> feat: main page mount fixed - 4

- src/pages/main/Main.tsx
> feat: jwt key recognize test

- src/App.tsx
- src/pages/main/Main.tsx
feat: jwt key recognize test - 2
> feat: jwt key recognize test - 2

- src/pages/main/Main.tsx
> feat: main page api call test

- src/components/common/TitleWrap.tsx
- src/components/detail/ExchangeWrap.tsx
- src/pages/detail/Detail.tsx
- src/pages/friend/Friend.tsx
- src/pages/main/Main.tsx
- src/styles/pages/_detail.scss
- src/styles/pages/_friend.scss
feat: detail page/friend page css fixed, friend isLunar default fixed
> feat: detail page/friend page css fixed, friend isLunar default fixed

- src/styles/pages/_main.scss
> feat: 메인페이지 필터 범위 수정
